{% set name = "wibl-python" %}
{% set version = "1.1.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CCOMJHC/WIBL/archive/refs/tags/{{ name }}-{{ version }}.tar.gz
  sha256: e092d83c6e323c41d12835abd52d7fc19d3fefa237285acd7c4cf529fc632de7

build:
  entry_points:
    - wibl = wibl.command.__main__:main
  noarch: python
  script: |
    {{ PYTHON }} -m pip install ./wibl-python/wibl-manager
    {{ PYTHON }} -m pip install ./wibl-python -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - csbschema ==1.1.2
    - gdal
    - matplotlib-base
    - boto3 ~=1.20
    - requests ~=2.31.0
    - numpy >=1.23.5
    - pynmea2 ~=1.18
    - pygmt ~=0.10.0
    - rasterio ~=1.3.0
    - geopandas
    - deepmerge
    - dataclasses-json ~=0.5.7
test:
  imports:
    - wibl
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
    - wibl --help

about:
  home: https://github.com/CCOMJHC/WIBL/tree/wibl-python-1.1.1/wibl-python
  summary: 'Python tools for WIBL low-cost data logger system.'
  description: |
    Python tools for WIBL low-cost data logger system. For more information on WIBL.
  license: MIT
  license_family: MIT
  license_file: wibl-python/LICENSE.txt
  doc_url: https://wibl.ccom.unh.edu/
  dev_url: https://github.com/CCOMJHC/WIBL

extra:
  recipe-maintainers:
    - selimnairb
    - brian-r-calder
